---
- name: kickoff scripted vCenterDeployment Qualys
  hosts: localhost
  connection: local
  tasks:
  - name: Execute raw shell command to kickoff vcsa Deployment with embedded_vCSA_on_VC.json
    raw: /Full_ISO_7.0.3/vcsa-cli-installer/lin64/vcsa-deploy install --acknowledge-ceip --accept-eula --no-esx-ssl-verify -v /Full_ISO_7.0.3/vcsa-cli-installer/lin64/embedded_vCSA_on_VC.json




  # ./vcsa-deploy install --acknowledge-ceip --accept-eula --no-esx-ssl-verify -v embedded_vCSA_on_VC.json
