
# Developed by Robert Ryan, North America Technology and Solution Center HPE
# This script is intended for testing/demo perposes and includes no warrenty or entitlements
---
- name: kickoff scripted vCenterDeployment Qualys
  hosts: localhost

  tasks:
   - name: Execute raw shell command to kickoff vcsa Deployment with embedded_vCSA_on_VC.json
     raw: /home/robert/qualys/Full_ISO_7.0.3/vcsa-cli-installer/lin64/vcsa-deploy install --acknowledge-ceip --accept-eula --no-esx-ssl-verify -v /home/robert/qualys/Full_ISO_7.0.3/vcsa-cli-installer/lin64/embedded_vCSA_on_VC.json
   - name: Wait for 5 minutes  
     pause:
       minutes: 5

- name: Datacenter Creation Tool
  hosts: localhost
  connection: local
  gather_facts: no
  vars: 
   vcenterip: '10.10.5.186'
   vcenter_hostname: 'administrator@vsphere.local'
   vcenter_password: 'HP1nvent!'
   new_dc_name: 'QualysDC'
   new_cl_name: 'QualysCL'
   esxi_serverip1: '10.10.0.180'
   esxi_serverip2: '10.10.0.181'
   esxi_serverip3: '10.10.0.182'
    
  tasks:
  - name: Creating New Datacenter
    community.vmware.vmware_datacenter:
     hostname: '{{ vcenterip }}'
     username: '{{ vcenter_hostname }}'
     password: '{{ vcenter_password }}'
     validate_certs: no
     datacenter_name: '{{ new_dc_name }}'
     state: present
    delegate_to: localhost
  - name: sleep for two seconds
    wait_for: 
      delay: 2
      timeout: 0
  - name: Create Cluster
    community.vmware.vmware_cluster:
     hostname: '{{ vcenterip }}'
     username: '{{ vcenter_hostname }}'
     password: '{{ vcenter_password }}'
     validate_certs: no
     datacenter_name: '{{ new_dc_name }}'
     cluster_name: '{{ new_cl_name }}'
     enable_ha: false
     enable_drs: false
     enable_vsan: false
    delegate_to: localhost
  - name: sleep for two seconds
    wait_for: 
      delay: 2
      timeout: 0
  - name: Add First ESXi Host to vCenter
    community.vmware.vmware_host:
     hostname: '{{ vcenterip }}'
     username: '{{ vcenter_hostname }}'
     password: '{{ vcenter_password }}'
     validate_certs: no
     datacenter: '{{ new_dc_name }}'
     cluster: '{{ new_cl_name }}'
     esxi_hostname: '{{ esxi_serverip1 }}'
     esxi_username: 'root'
     esxi_password: 'HP1nvent!'
     force_connection: yes
     state: present
    delegate_to: localhost
  - name: sleep for ten seconds
    wait_for: 
      delay: 10
      timeout: 0
  - name: sleep for two seconds
    wait_for: 
      delay: 2
      timeout: 0
  - name: Add second ESXi Host to vCenter
    community.vmware.vmware_host:
     hostname: '{{ vcenterip }}'
     username: '{{ vcenter_hostname }}'
     password: '{{ vcenter_password }}'
     validate_certs: no
     datacenter: '{{ new_dc_name }}'
     cluster: '{{ new_cl_name }}'
     esxi_hostname: '{{ esxi_serverip2 }}'
     esxi_username: 'root'
     esxi_password: 'HP1nvent!'
     force_connection: yes
     state: present
    delegate_to: localhost
  - name: sleep for ten seconds
    wait_for: 
      delay: 10
      timeout: 0
  - name: sleep for two seconds
    wait_for: 
      delay: 2
      timeout: 0
  - name: Add third ESXi Host to vCenter
    community.vmware.vmware_host:
     hostname: '{{ vcenterip }}'
     username: '{{ vcenter_hostname }}'
     password: '{{ vcenter_password }}'
     validate_certs: no
     datacenter: '{{ new_dc_name }}'
     cluster: '{{ new_cl_name }}'
     esxi_hostname: '{{ esxi_serverip3 }}'
     esxi_username: 'root'
     esxi_password: 'HP1nvent!'
     force_connection: yes
     state: present
    delegate_to: localhost
  - name: sleep for ten seconds
    wait_for: 
      delay: 10
      timeout: 0

  # - name: Deploy Windows 2019 Jump Server VM loaded with all software
  #   community.vmware.vmware_deploy_ovf:
  #     hostname: '{{ vcenter_ip }}'
  #     username: '{{ vcenter_hostname }}'
  #     password: '{{ vcenter_password }}'
  #     validate_certs: no
  #     datacenter: '{{ new_dc_name }}'
  #     esxi_hostname: '{{ esxi_serverip }}'
  #     datastore: datastore1
  #     disk_provisioning: thin
  #     ovf: /home/robert/Documents/playbooks/runbook1_Create-DC-CL-win19Jump/Wind2019JumpVM-Oct2021.ova
  #     name: Win2019-JumpVM
  #   delegate_to: localhost


   # ./vcsa-deploy install --acknowledge-ceip --accept-eula --no-esx-ssl-verify -v embedded_vCSA_on_VC.json
