---
- hosts: all
  gather_facts: false
  connection: network_cli
  become: yes
  become_method: enable
  tasks: 
    - name: Make splitter ports on switch interfaces
      onyx_config:
        commands: interface ethernet {{ item }} module-type qsfp-split-4 force
      loop:
        - 1/1
        - 1/3
        - 1/5
        - 1/7
        - 1/9

    - name: Save the config
      onyx_config:
        commands: 
          - write memory




#          - interface ethernet "{{ item }}" module-type qsfp-split-4 force
#          - module-type qsfp-split-4 force
#          - no shutdown
#          - speed 40000 force
#          - mtu 1500 force
#          - exit
#          - write memory
#          loop:
#           - 1/23
#           - 1/25
#    - name: Show version of os on remote switch
#      onyx_config:
#       commands: 
